#!/usr/bin/env bash

# Make sure we're running in this directory
cd $(dirname $0)

# Setup the domain
DOMAIN="$1"
mkdir "${DOMAIN}"

# Generate passwordless private key
openssl genrsa -des3 -passout pass:x -out "${DOMAIN}/private.pass.pem" 4096
openssl rsa -passin pass:x -in "${DOMAIN}/private.pass.pem" -out "${DOMAIN}/private.pem"
rm "${DOMAIN}/private.pass.pem"

# Generate certificate signature request
openssl req -new -key "${DOMAIN}/private.pem" -out "${DOMAIN}/request.pem" -config <(cat openssl.cnf <(printf "\nCN = ${DOMAIN}\n[alt_names]\nDNS.1 = ${DOMAIN}\n[SAN]\nsubjectAltName=DNS:${DOMAIN}")) -extensions 'v3_req'

# Generate certificate
openssl x509 -req -sha256 -days 7300 -in "${DOMAIN}/request.pem" -signkey "${DOMAIN}/private.pem" -out "${DOMAIN}/certificate.pem"
